name: wps
channels:
- defaults
- birdhouse
- conda-forge
dependencies:
- python=2.7
- pyopenssl=16.2.0
- cryptography=1.5.3
#- pyyaml=3.11
- curl=7.45.0
# buildout
- mako=1.0.4
# tests
- pytest
- flake8
# ipython
- ipython
# docs
- sphinx=1.4.1
- sphinx_rtd_theme
# wps
- pywps=4.0.0_rc2
- nginx=1.10.1
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.1.2
# esmvaltool
- esgf-pyclient
- pip:
  - genshi==0.7
  - sphinx-autoapi==0.4.0
  - eventlet==0.19.0
