name: wps
channels:
- defaults
- birdhouse
- conda-forge
dependencies:
- python=2.7
- pyopenssl
- cryptography
# buildout
- mako
# tests
- pytest
- flake8
# ipython
- ipython
# docs
- sphinx
- sphinx_rtd_theme
# wps
- pywps=4.0.0
- nginx=1.10.1
- supervisor=3.3.1
- gunicorn=19.1.0
- gevent=1.1.2
# esmvaltool
- esgf-pyclient
- pip:
  - genshi==0.7
  - sphinx-autoapi==0.4.0
  - eventlet==0.19.0
